// lib/objectbox.dart
import 'package:path_provider/path_provider.dart'; // For finding app directory
import 'package:objectbox/objectbox.dart'; // The ObjectBox package
import 'objectbox.g.dart'; // Generated by `flutter pub run build_runner build`

/// Global object for accessing the ObjectBox Store.
late Store objectbox;

/// Initializes the ObjectBox Store.
Future<void> initializeObjectBox() async {
  // Get a directory for the database files, specific to your platform.
  final appDocumentDir = await getApplicationDocumentsDirectory();
  // The path where the database files will be stored.
  final dbPath = '${appDocumentDir.path}/objectbox';

  // Create the store using the generated model.
  objectbox = await openStore(directory: dbPath);
}

// Ensure you run `flutter pub run build_runner build` after creating or modifying entities.